# Generated by Django 6.0.3 on 2026-03-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('other', 'Другое')])),
                ('photo', models.ImageField(blank=True, upload_to='pets/')),
                ('birth_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feeding', 'Кормление'), ('walk', 'Прогулка'), ('vet', 'Ветеринар'), ('medicine', 'Лекарства'), ('weight', 'Вес'), ('grooming', 'Груминг')])),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcare_tracker.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feeding', 'Кормление'), ('walk', 'Прогулка'), ('vet', 'Ветеринар'), ('medicine', 'Лекарства'), ('weight', 'Вес'), ('grooming', 'Груминг')])),
                ('remind_at', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petcare_tracker.pet')),
            ],
        ),
    ]
