# Generated by Django 6.0.3 on 2026-03-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='petcare_tracker.pet'),
        ),
    ]
