# Generated by Django 6.0.3 on 2026-03-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare_tracker', '0002_alter_habitlog_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
